In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import random
import numpy as np
pd.set_option('display.max_colwidth', None)

In [16]:
df = pd.read_csv("tweet.csv")
del df[df.columns[0]]
df

sentimen  \
0     negatif   
1      netral   
2      netral   
3     positif   
4     negatif   
...       ...   
1810   netral   
1811   netral   
1812   netral   
1813   netral   
1814   netral   

                                                                                                                                                                                                                                                     tweet  
0                                                      Kata @prabowo Indonesia tidak dihargai bangsa asing!   Berita ini 👇 pasti hoax buatan penguasa, ya kan @rockygerung?😜 https://twitter.com/mediaindonesia/status/1117575436337160192?s=21 …  
1                                                                                                                                                            Batuan Langka, Tasbih Jokowi Hadiah dari Habib Luthfi Seharga Mercy?  http://dlvr.it/R2pvZV   
2                                                                                                                           Di era Jokowi, ekonomi Indonesia semakin baik. #01IndonesiaMaju #JokowiLagi #JokowiMenangTotalDebat pic.twitter.com/W2ythnxsTp  
3                                                                                                                         Bagi Sumatera Selatan, Asian Games berdampak pd ekonomi langsung diprediksi mencapai 18,5 triliun. Indonesia maju, Jokowi hebat!  
4     Negara kita ngutang buat bngun infrastruktur yang udah dipake masyarakat, terus masyarakatnya ngeluh karena negara ngutang, setiap negara itu pasti ngutang,  utang bisa dibayar kalo negara dapet penghasilan. Penghasilan negara itu ya dari pajak  
...                                                                                                                                                                                                                                                    ...  
1810                                                                                                                                                   Negarawan sejati sll bangga dan mengedepankan harga diri bangsanya yg berdaulat  #2019GantiPresiden  
1811                                                                                                                                                                      1. HRS ceramah di Damai Indonesiaku 2. Perekonomian makin membaik.  #PutihkanGBK  
1812                                                                                                  Mari bangun bangsa dgn mendukung perekonomian negara bersama Pak Jokowi. Ayo kerja!  https://twitter.com/KaskusLoker/status/1111643312241295363 …  
1813                                                                                                                             Bantu majukan perekonomian bangsa bersama Pak Jokowi, yuk!  https://twitter.com/BKNSquare/status/1113655944955588610 …  
1814                                                                                                    Pak @jokowi mengubah cara pandang ekonomi. Kini semua orang terhubung, sehingga Indonesia menjadi lebih produktif dan efisien. #MenyatuPutihJokowi  

[1815 rows x 2 columns]

In [3]:
df = pd.DataFrame(np.repeat(df.values, 2, axis=0), columns=df.columns)
df

sentimen  \
0     negatif   
1     negatif   
2      netral   
3      netral   
4      netral   
...       ...   
3625   netral   
3626   netral   
3627   netral   
3628   netral   
3629   netral   

                                                                                                                                                                                                    tweet  
0     Kata @prabowo Indonesia tidak dihargai bangsa asing!   Berita ini 👇 pasti hoax buatan penguasa, ya kan @rockygerung?😜 https://twitter.com/mediaindonesia/status/1117575436337160192?s=21 …  
1     Kata @prabowo Indonesia tidak dihargai bangsa asing!   Berita ini 👇 pasti hoax buatan penguasa, ya kan @rockygerung?😜 https://twitter.com/mediaindonesia/status/1117575436337160192?s=21 …  
2                                                                                                           Batuan Langka, Tasbih Jokowi Hadiah dari Habib Luthfi Seharga Mercy?  http://dlvr.it/R2pvZV   
3                                                                                                           Batuan Langka, Tasbih Jokowi Hadiah dari Habib Luthfi Seharga Mercy?  http://dlvr.it/R2pvZV   
4                                                                          Di era Jokowi, ekonomi Indonesia semakin baik. #01IndonesiaMaju #JokowiLagi #JokowiMenangTotalDebat pic.twitter.com/W2ythnxsTp  
...                                                                                                                                                                                                   ...  
3625                                                 Mari bangun bangsa dgn mendukung perekonomian negara bersama Pak Jokowi. Ayo kerja!  https://twitter.com/KaskusLoker/status/1111643312241295363 …  
3626                                                                            Bantu majukan perekonomian bangsa bersama Pak Jokowi, yuk!  https://twitter.com/BKNSquare/status/1113655944955588610 …  
3627                                                                            Bantu majukan perekonomian bangsa bersama Pak Jokowi, yuk!  https://twitter.com/BKNSquare/status/1113655944955588610 …  
3628                                                   Pak @jokowi mengubah cara pandang ekonomi. Kini semua orang terhubung, sehingga Indonesia menjadi lebih produktif dan efisien. #MenyatuPutihJokowi  
3629                                                   Pak @jokowi mengubah cara pandang ekonomi. Kini semua orang terhubung, sehingga Indonesia menjadi lebih produktif dan efisien. #MenyatuPutihJokowi  

[3630 rows x 2 columns]

In [18]:
df.sentimen.value_counts()

sentimen
positif    612
netral     607
negatif    596
Name: count, dtype: int64

In [19]:
df['tweet']=df['tweet'].str.lower()
df['tweet'].tail()

1810                                                     negarawan sejati sll bangga dan mengedepankan harga diri bangsanya yg berdaulat  #2019gantipresiden
1811                                                                        1. hrs ceramah di damai indonesiaku 2. perekonomian makin membaik.  #putihkangbk
1812    mari bangun bangsa dgn mendukung perekonomian negara bersama pak jokowi. ayo kerja!  https://twitter.com/kaskusloker/status/1111643312241295363â â€¦
1813                               bantu majukan perekonomian bangsa bersama pak jokowi, yuk!  https://twitter.com/bknsquare/status/1113655944955588610â â€¦
1814      pak @jokowi mengubah cara pandang ekonomi. kini semua orang terhubung, sehingga indonesia menjadi lebih produktif dan efisien. #menyatuputihjokowi
Name: tweet, dtype: object

In [20]:
import string
english_punctuations = string.punctuation
punctuations_list = english_punctuations
def cleaning_punctuations(text):
    translator = str.maketrans('', '', punctuations_list)
    return text.translate(translator)
df['tweet']= df['tweet'].apply(lambda x: cleaning_punctuations(x))
df['tweet'].tail()

1810                                               negarawan sejati sll bangga dan mengedepankan harga diri bangsanya yg berdaulat  2019gantipresiden
1811                                                                     1 hrs ceramah di damai indonesiaku 2 perekonomian makin membaik  putihkangbk
1812      mari bangun bangsa dgn mendukung perekonomian negara bersama pak jokowi ayo kerja  httpstwittercomkaskuslokerstatus1111643312241295363â â€¦
1813                                 bantu majukan perekonomian bangsa bersama pak jokowi yuk  httpstwittercombknsquarestatus1113655944955588610â â€¦
1814    pak jokowi mengubah cara pandang ekonomi kini semua orang terhubung sehingga indonesia menjadi lebih produktif dan efisien menyatuputihjokowi
Name: tweet, dtype: object

In [21]:
import re
def cleaning_repeating_char(text):
    return re.sub(r'(.)1+', r'1', text)
df['tweet'] = df['tweet'].apply(lambda x: cleaning_repeating_char(x))
df['tweet'].tail()

1810                                                negarawan sejati sll bangga dan mengedepankan harga diri bangsanya yg berdaulat  219gantipresiden
1811                                                                     1 hrs ceramah di damai indonesiaku 2 perekonomian makin membaik  putihkangbk
1812            mari bangun bangsa dgn mendukung perekonomian negara bersama pak jokowi ayo kerja  httpstwittercomkaskuslokerstatu16431221295363â â€¦
1813                                     bantu majukan perekonomian bangsa bersama pak jokowi yuk  httpstwittercombknsquarestatu1365594495558810â â€¦
1814    pak jokowi mengubah cara pandang ekonomi kini semua orang terhubung sehingga indonesia menjadi lebih produktif dan efisien menyatuputihjokowi
Name: tweet, dtype: object

In [22]:
def cleaning_URLs(data):
    return re.sub('((www.[^s]+)|(https?://[^s]+))',' ',data)
df['tweet'] = df['tweet'].apply(lambda x: cleaning_URLs(x))
df['tweet'].tail()

1810                                                negarawan sejati sll bangga dan mengedepankan harga diri bangsanya yg berdaulat  219gantipresiden
1811                                                                     1 hrs ceramah di damai indonesiaku 2 perekonomian makin membaik  putihkangbk
1812            mari bangun bangsa dgn mendukung perekonomian negara bersama pak jokowi ayo kerja  httpstwittercomkaskuslokerstatu16431221295363â â€¦
1813                                     bantu majukan perekonomian bangsa bersama pak jokowi yuk  httpstwittercombknsquarestatu1365594495558810â â€¦
1814    pak jokowi mengubah cara pandang ekonomi kini semua orang terhubung sehingga indonesia menjadi lebih produktif dan efisien menyatuputihjokowi
Name: tweet, dtype: object

In [23]:
def cleaning_numbers(data):
    return re.sub('[0-9]+', '', data)
df['tweet']= df['tweet'].apply(lambda x: cleaning_numbers(x))
df['tweet'].tail()

1810                                                   negarawan sejati sll bangga dan mengedepankan harga diri bangsanya yg berdaulat  gantipresiden
1811                                                                        hrs ceramah di damai indonesiaku  perekonomian makin membaik  putihkangbk
1812                          mari bangun bangsa dgn mendukung perekonomian negara bersama pak jokowi ayo kerja  httpstwittercomkaskuslokerstatuâ â€¦
1813                                                     bantu majukan perekonomian bangsa bersama pak jokowi yuk  httpstwittercombknsquarestatuâ â€¦
1814    pak jokowi mengubah cara pandang ekonomi kini semua orang terhubung sehingga indonesia menjadi lebih produktif dan efisien menyatuputihjokowi
Name: tweet, dtype: object

In [24]:
df.sentimen.value_counts()

sentimen
positif    612
netral     607
negatif    596
Name: count, dtype: int64

In [25]:
df.sentimen = df.sentimen.map({'negatif':0, 'positif':1, 'netral':2})

In [26]:
df

sentimen  \
0            0   
1            2   
2            2   
3            1   
4            0   
...        ...   
1810         2   
1811         2   
1812         2   
1813         2   
1814         2   

                                                                                                                                                                                                                                                 tweet  
0                                                                                      kata prabowo indonesia tidak dihargai bangsa asing   berita ini ðÿ‘‡ pasti hoax buatan penguasa ya kan rockygerungðÿ˜œ httpstwittercommediaindonesiastatusâ â€¦  
1                                                                                                                                                                batuan langka tasbih jokowi hadiah dari habib luthfi seharga mercy  httpdlvritrpvzvâ   
2                                                                                                                                  di era jokowi ekonomi indonesia semakin baik indonesiamaju jokowilagi jokowimenangtotaldebat pictwittercomwythnxstp  
3                                                                                                                              bagi sumatera selatan asian games berdampak pd ekonomi langsung diprediksi mencapai triliun indonesia maju jokowi hebat  
4     negara kita ngutang buat bngun infrastruktur yang udah dipake masyarakat terus masyarakatnya ngeluh karena negara ngutang setiap negara itu pasti ngutang  utang bisa dibayar kalo negara dapet penghasilan penghasilan negara itu ya dari pajak  
...                                                                                                                                                                                                                                                ...  
1810                                                                                                                                                    negarawan sejati sll bangga dan mengedepankan harga diri bangsanya yg berdaulat  gantipresiden  
1811                                                                                                                                                                         hrs ceramah di damai indonesiaku  perekonomian makin membaik  putihkangbk  
1812                                                                                                                           mari bangun bangsa dgn mendukung perekonomian negara bersama pak jokowi ayo kerja  httpstwittercomkaskuslokerstatuâ â€¦  
1813                                                                                                                                                      bantu majukan perekonomian bangsa bersama pak jokowi yuk  httpstwittercombknsquarestatuâ â€¦  
1814                                                                                                     pak jokowi mengubah cara pandang ekonomi kini semua orang terhubung sehingga indonesia menjadi lebih produktif dan efisien menyatuputihjokowi  

[1815 rows x 2 columns]

In [27]:
df_train, df_test = train_test_split(df, test_size=0.2)

In [28]:
df_train

sentimen  \
924          0   
1426         0   
572          1   
1187         1   
97           0   
...        ...   
1425         0   
1715         2   
531          0   
941          2   
353          0   

                                                                                                                                                                                                                                                                                                       tweet  
924                                                                           nahdlatululama heran  prabowo bilang mau mau tingkatkan penerimaan pajak  kok sandi bilang akan menghapus pajak dr pengusaha kecil  ini kok bertolak belakang kebijakan nya  coba deh dengar ulang debat nya masalah pajak itu  
1426  pakta integritas wo pulangkan nb brizik jd menag kilafah bebaskan ulama kriminal prabowoketurunankafircinamonster  hpl psl  tp wounoorbakuasailahanluassimpandipanamaserakahganasionalis  gaji gadiambil tp tunjangan milyaranbln diambil munafik menangradikalorbaasengberkuasa pictwittercomzdlyaqiv  
572                                   loh itu gusdur yah saya dukung prabowo karna fatwah gusdur kalau pak prabowo presiden yg paking ikhlas insya allah tahun ini terbikti meski beliau pernah kalah berkali beliau tetap ikhlas melanjutkn perjuangantdi mlm sya dengar dari sandiuno tdk akan terima gaji  
1187                                                                now its yourturnbro please say to them that prabowo  sandi tidak akan ambil gaji sebagai seorang presiden dan wapres dan gajinya akan disumbangkan ke kaum dhuafakerennn kan bukti bahwa beliau akan wakafkan harta dan jiwanya utk nkri  
97                                                                                                                                                                                                                prabowosandi sepakat ekonomi indonesia salah arah  httpdlvritrpfnâ  pictwittercomuyuisdrur  
...                                                                                                                                                                                                                                                                                                      ...  
1425                                                                                                                                                                                                                                                         jokowi nanya ekonomi digital ga penting wadooo   
1715                                                                                                                                             pajak itu bisa bocor karena dari manusia untuk negara zakat itu kalo mau bikin bocor pasti mikir soalnya resiko diumumkan di masjid dan mushala beranipilih  
531                                                    overheard   ðÿ‘§ ehmm jokowi bagus sih di segi pembangunan ðÿ™ž iyaa ekonomi jg makin maju ðÿ‘§ tapi ya gue males sih milih dia soalnya pembangunannya ga gua rasain dia bikin jalan tol gua kan kemana naik motor  awas aja lu mudik lewat tol ya bu  
941                                                                                                       prabowo sebut garuda sulit untung tkn pengaruh harga avtur  httpsbisnistempocoreaprabowosebutgarudasulituntungtknpengaruhhargaavturutmsourcedigitalmarketingutmmediumtwitterutmcampaigndlvritâ â€¦  
353                                                                                                                                                                             kenapa ekonominya   bukannya target  kalau idola elo bicara  digit itu gimana   terbukti kan ane bilang tegas ya seperti apa  

[1452 rows x 2 columns]

In [29]:
df_train = pd.DataFrame(np.repeat(df_train.values, 2, axis=0), columns=df_train.columns)
df_train

sentimen  \
0           0   
1           0   
2           0   
3           0   
4           1   
...       ...   
2899        0   
2900        2   
2901        2   
2902        0   
2903        0   

                                                                                                                                                                                                                                                                                                       tweet  
0                                                                             nahdlatululama heran  prabowo bilang mau mau tingkatkan penerimaan pajak  kok sandi bilang akan menghapus pajak dr pengusaha kecil  ini kok bertolak belakang kebijakan nya  coba deh dengar ulang debat nya masalah pajak itu  
1                                                                             nahdlatululama heran  prabowo bilang mau mau tingkatkan penerimaan pajak  kok sandi bilang akan menghapus pajak dr pengusaha kecil  ini kok bertolak belakang kebijakan nya  coba deh dengar ulang debat nya masalah pajak itu  
2     pakta integritas wo pulangkan nb brizik jd menag kilafah bebaskan ulama kriminal prabowoketurunankafircinamonster  hpl psl  tp wounoorbakuasailahanluassimpandipanamaserakahganasionalis  gaji gadiambil tp tunjangan milyaranbln diambil munafik menangradikalorbaasengberkuasa pictwittercomzdlyaqiv  
3     pakta integritas wo pulangkan nb brizik jd menag kilafah bebaskan ulama kriminal prabowoketurunankafircinamonster  hpl psl  tp wounoorbakuasailahanluassimpandipanamaserakahganasionalis  gaji gadiambil tp tunjangan milyaranbln diambil munafik menangradikalorbaasengberkuasa pictwittercomzdlyaqiv  
4                                     loh itu gusdur yah saya dukung prabowo karna fatwah gusdur kalau pak prabowo presiden yg paking ikhlas insya allah tahun ini terbikti meski beliau pernah kalah berkali beliau tetap ikhlas melanjutkn perjuangantdi mlm sya dengar dari sandiuno tdk akan terima gaji  
...                                                                                                                                                                                                                                                                                                      ...  
2899                                                   overheard   ðÿ‘§ ehmm jokowi bagus sih di segi pembangunan ðÿ™ž iyaa ekonomi jg makin maju ðÿ‘§ tapi ya gue males sih milih dia soalnya pembangunannya ga gua rasain dia bikin jalan tol gua kan kemana naik motor  awas aja lu mudik lewat tol ya bu  
2900                                                                                                      prabowo sebut garuda sulit untung tkn pengaruh harga avtur  httpsbisnistempocoreaprabowosebutgarudasulituntungtknpengaruhhargaavturutmsourcedigitalmarketingutmmediumtwitterutmcampaigndlvritâ â€¦  
2901                                                                                                      prabowo sebut garuda sulit untung tkn pengaruh harga avtur  httpsbisnistempocoreaprabowosebutgarudasulituntungtknpengaruhhargaavturutmsourcedigitalmarketingutmmediumtwitterutmcampaigndlvritâ â€¦  
2902                                                                                                                                                                            kenapa ekonominya   bukannya target  kalau idola elo bicara  digit itu gimana   terbukti kan ane bilang tegas ya seperti apa  
2903                                                                                                                                                                            kenapa ekonominya   bukannya target  kalau idola elo bicara  digit itu gimana   terbukti kan ane bilang tegas ya seperti apa  

[2904 rows x 2 columns]

In [30]:
df_test

sentimen  \
500          2   
428          1   
146          2   
399          1   
1362         0   
...        ...   
1554         1   
702          0   
424          2   
1253         0   
1510         2   

                                                                                                                                                                                                                                                                        tweet  
500                                                                                                namun sebagai anak seorang ahli ekonomi fenomena ransel besar prabowo juga sesuatu yang wajar bagi yunus prabowo sandiuno prabowosandi indonesiamenang indonesiaadilmakmur  
428                                                                                                 dengan memilih prabowo sandi anda akan beramal selama  th karena gaji mereka akan disumbangkan untuk kaum dhuafa dan anak yatim aamiin ðÿ‘†ðÿ‘† thegreatcampaignofprabowo  
146                                                                                                         pemerintah jokowi juga menyebut masa depan ekonomi indonesia di tangan anakanak muda kreatif  httpsbitlyuauzkrâ  pilihorangbaik pilihjelasislamnya pilihbajuputih  
399                                                                                                                                             mahal ini kelassss masyaallah bila terpilih prabowosandi janji tak ambil gaji catatan httpstwittercomranupsprosandistatuâ â€¦  
1362                                                             mebeeel piyeeee paak sepiii raaa prabowo menang mebelmu mebelku kabeh pedagang mebeel rameee dagangane ekonomine apik wong do tukuu penak dodolan mebel jaman jokowii ngeluu siraah jaman sby jooss gandooss  
...                                                                                                                                                                                                                                                                       ...  
1554                                                                                                                                                                 walaupun usaha saya naik turun saya tidak memikirkan ekonomi melemah bagi saya tetap jokowi my president  
702                                                                                                                                                                                            pak jokowi tolong kondisikan harga pringles original yang ga turun  saya sedih  
424                                                                                                                                                                             di jaman sby harga pupuk murah di jaman bpk pupuk mahal dan langka bisa di jelas kn kenapa pk  
1253  itulah yg tdk masuk logika cebongprabowo sandi berbicara mslh lap kerja dan harga bkn krna mrka miskinmrka kayatpi mrka peduli nasib rakyat yg cuma krja bertahan seadanyabgtu jgalah sysy peduli nasibmu sajabiar bisa hidup tdk skedar ngejar nasi bngkus yourturnbro  
1510                           sandiuno jokowi bangun bendungan ctk sawah tali air utk tingkatkan produk beras bkn gagahan begini caranya kerja hrs bertahap  saya akan bangun ekonomi segera dinikmati rakyat enak aja spt balik tekapak tangan memangnya punya lampu aladin  

[363 rows x 2 columns]

In [370]:
#train_tweet, test_tweet, train_sentimen, test_sentimen = train_test_split(df['tweet'].to_numpy(), df['sentimen'].to_numpy(), test_size=0.2)

## Converting text into numbers (Text Vectorization(=)

In [31]:
import tensorflow as tf
from tensorflow.keras.layers import TextVectorization # after TensorFlow 2.6

# Use the default TextVectorization variables
text_vectorizer = TextVectorization(max_tokens=None, # how many words in the vocabulary (all of the different words in your text)
                                    standardize="lower_and_strip_punctuation", # how to process text
                                    split="whitespace", # how to split tokens
                                    ngrams=None, # create groups of n-words?
                                    output_mode="int", # how to map tokens to numbers
                                    output_sequence_length=None) # how long should the output sequence of tokens be?
                                    # pad_to_max_tokens=True) # Not valid if using max_tokens=None

In [57]:
type(df_train['sentimen'])

pandas.core.series.Series

In [372]:
# Find average number of tokens (words) in training Tweets
round(sum([len(i.split()) for i in train_tweet])/len(train_tweet))

24

In [33]:
max_vocab_length = 10000 # max number of words to have in our vocabulary
max_length = 24 # max length our sequences will be (e.g. how many words from a Tweet does our model see?)

text_vectorizer = TextVectorization(max_tokens=max_vocab_length,
                                    standardize="lower_and_strip_punctuation",
                                     split="whitespace",
                                    output_mode="int",
                                    output_sequence_length=max_length)

In [374]:
text_vectorizer

In [34]:
df_train.tweet

0                                                                               nahdlatululama heran  prabowo bilang mau mau tingkatkan penerimaan pajak  kok sandi bilang akan menghapus pajak dr pengusaha kecil  ini kok bertolak belakang kebijakan nya  coba deh dengar ulang debat nya masalah pajak itu
1                                                                               nahdlatululama heran  prabowo bilang mau mau tingkatkan penerimaan pajak  kok sandi bilang akan menghapus pajak dr pengusaha kecil  ini kok bertolak belakang kebijakan nya  coba deh dengar ulang debat nya masalah pajak itu
2       pakta integritas wo pulangkan nb brizik jd menag kilafah bebaskan ulama kriminal prabowoketurunankafircinamonster  hpl psl  tp wounoorbakuasailahanluassimpandipanamaserakahganasionalis  gaji gadiambil tp tunjangan milyaranbln diambil munafik menangradikalorbaasengberkuasa pictwittercomzdlyaqiv
3       pakta integritas wo pulangkan nb brizik jd menag kilafah bebaskan ulama kriminal pr

In [47]:
# Fit the text vectorizer to the training text
text_vectorizer.adapt(df_train.tweet.to_numpy())

In [48]:
#train_tweet[0]
df_train.tweet[0]

'nahdlatululama heran  prabowo bilang mau mau tingkatkan penerimaan pajak  kok sandi bilang akan menghapus pajak dr pengusaha kecil  ini kok bertolak belakang kebijakan nya  coba deh dengar ulang debat nya masalah pajak itu'

In [49]:
sample_sentence = df_train.tweet[0]
text_vectorizer([sample_sentence])

<tf.Tensor: shape=(1, 24), dtype=int64, numpy=
array([[4444, 1049,    5,   89,   25,   25,  413,  979,   62,  117,   18,
          89,   14, 1239,   62,  123,  320,  173,   13,  117, 6774, 2605,
         257,   57]], dtype=int64)>

In [50]:
# Get the unique words in the vocabulary
words_in_vocab = text_vectorizer.get_vocabulary()
top_5_words = words_in_vocab[:10] # most common tokens (notice the [UNK] token for "unknown" words)
bottom_5_words = words_in_vocab[-10:] # least common tokens
print(f"Number of words in vocab: {len(words_in_vocab)}")
print(f"Top 5 most common words: {top_5_words}") 
print(f"Bottom 5 least common words: {bottom_5_words}")

Number of words in vocab: 7174
Top 5 most common words: ['', '[UNK]', 'ekonomi', 'jokowi', 'dan', 'prabowo', 'yg', 'di', 'pak', 'gaji']
Bottom 5 least common words: ['abdul', 'abdillah', 'abdalla', 'abangâ²', 'abah', 'abadi', 'aaminnnn', 'aamiinn', 'aagympilihprabowosandi', 'aaamiin']


## Creating an Embedding using an Embedding Layer

In [51]:
tf.random.set_seed(42)
from tensorflow.keras import layers

embedding = layers.Embedding(input_dim=max_vocab_length, # set input shape
                             output_dim=64, # set size of embedding vector
                             embeddings_initializer="uniform", # default, intialize randomly
                             input_length=max_length, # how long is each input
                             name="embedding_1") 

embedding

In [41]:
# Get a random sentence from training set
random_sentence = random.choice(df_train.tweet)
print(f"Original text:\n{random_sentence}\
      \n\nEmbedded version:")
# Embed the random sentence (turn it into numerical representation)
sample_embed = embedding(text_vectorizer([random_sentence]))
sample_embed

Original text:
barangkali karena trend pertumbuhan ekonomi  menurun makanya bukan salah pak jokowi      

Embedded version:


<tf.Tensor: shape=(1, 24, 64), dtype=float32, numpy=
array([[[-0.03082364, -0.04399418, -0.01377869, ...,  0.02217642,
          0.00119333,  0.03113574],
        [-0.03478582,  0.01202619,  0.04426671, ..., -0.02995819,
         -0.00033432,  0.00980492],
        [ 0.02458104,  0.00179539,  0.02629634, ...,  0.02716828,
          0.03564088, -0.03674383],
        ...,
        [-0.01164757, -0.00856902, -0.01077387, ...,  0.03901218,
          0.04419729, -0.04069805],
        [-0.01164757, -0.00856902, -0.01077387, ...,  0.03901218,
          0.04419729, -0.04069805],
        [-0.01164757, -0.00856902, -0.01077387, ...,  0.03901218,
          0.04419729, -0.04069805]]], dtype=float32)>

In [42]:
sample_embed[0][0]

<tf.Tensor: shape=(64,), dtype=float32, numpy=
array([-0.03082364, -0.04399418, -0.01377869, -0.04008532,  0.04154402,
       -0.03221127, -0.04377961,  0.04970271, -0.02009552, -0.04605513,
       -0.02143475,  0.01888082, -0.02559466, -0.0245685 , -0.02618383,
       -0.01529046,  0.01713106, -0.03489461, -0.01174982, -0.02301276,
       -0.00133928,  0.02770307,  0.03051854,  0.02153102, -0.03210928,
       -0.03827928, -0.00222371, -0.04246115, -0.00463669, -0.03752853,
       -0.04157047, -0.03627113,  0.03302734,  0.02015588,  0.02756115,
       -0.02279891, -0.02015086, -0.03837994,  0.02065061,  0.00292379,
       -0.00230926,  0.01361388, -0.02195923,  0.04619691, -0.01407833,
        0.01077317,  0.0145652 , -0.04411516,  0.01378013,  0.02096942,
       -0.00677762, -0.01763888, -0.04074979, -0.00287559, -0.00443573,
       -0.04155033, -0.04483011,  0.00082704, -0.00946669,  0.02142392,
        0.0092196 ,  0.02217642,  0.00119333,  0.03113574], dtype=float32)>

In [382]:
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def calculate_results(y_true, y_pred):
  """
  Calculates model accuracy, precision, recall and f1 score of a binary classification model.

  Args:
  -----
  y_true = true labels in the form of a 1D array
  y_pred = predicted labels in the form of a 1D array

  Returns a dictionary of accuracy, precision, recall, f1-score.
  """
  # Calculate model accuracy
  model_accuracy = accuracy_score(y_true, y_pred) * 100
  # Calculate model precision, recall and f1 score using "weighted" average
  model_precision, model_recall, model_f1, _ = precision_recall_fscore_support(y_true, y_pred, average="weighted")
  model_results = {"accuracy": model_accuracy,
                  "precision": model_precision,
                  "recall": model_recall,
                  "f1": model_f1}
  return model_results

In [43]:
tf.random.set_seed(42)
from tensorflow.keras import layers
model_2_embedding = layers.Embedding(input_dim=max_vocab_length,
                                     output_dim=64,
                                     embeddings_initializer="uniform",
                                     input_length=max_length,
                                     name="embedding_2")


# Create LSTM model
inputs = layers.Input(shape=(1,), dtype="string")
x = text_vectorizer(inputs)
x = model_2_embedding(x)
#x = layers.SpatialDropout1D(0.4)(x)
print(x.shape)
# x = layers.LSTM(64, return_sequences=True)(x) # return vector for each word in the Tweet (you can stack RNN cells as long as return_sequences=True)
x = layers.LSTM(32)(x) # return vector for whole sequence

print(x.shape)
# x = layers.Dense(64, activation="relu")(x) # optional dense layer on top of output of LSTM cell
outputs = layers.Dense(3, activation="softmax")(x)
model_2 = tf.keras.Model(inputs, outputs, name="model_2_LSTM")

(None, 24, 64)
(None, 32)


In [44]:
# Compile model
model_2.compile(loss="sparse_categorical_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])


In [45]:
model_2.summary()

Model: "model_2_LSTM"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_2 (Text  (None, 24)                0         
 Vectorization)                                                  
                                                                 
 embedding_2 (Embedding)     (None, 24, 64)            640000    
                                                                 
 lstm (LSTM)                 (None, 32)                12416     
                                                                 
 dense (Dense)               (None, 3)                 99        
                                                                 
Total params: 652515 (2.49 MB)
Trainable params: 652515 (2.49 MB)
Non-trainable params: 0 (0.00 Byte)
__________________

In [60]:
# Fit model
model_2_history = model_2.fit(df_train.tweet,
                              df_train.sentimen.astype(np.float32),
                              epochs=10,
                               validation_data=(df_test.tweet, df_test.sentimen.astype(np.float32)),
                              )

Epoch 1/10
91/91 [==============================] - 13s 67ms/step - loss: 0.9724 - accuracy: 0.5427 - val_loss: 0.9007 - val_accuracy: 0.6171
Epoch 2/10
91/91 [==============================] - 5s 50ms/step - loss: 0.3791 - accuracy: 0.8740 - val_loss: 1.1788 - val_accuracy: 0.5207
Epoch 3/10
91/91 [==============================] - 5s 51ms/step - loss: 0.1009 - accuracy: 0.9704 - val_loss: 1.5513 - val_accuracy: 0.5399
Epoch 4/10
91/91 [==============================] - 5s 57ms/step - loss: 0.0507 - accuracy: 0.9876 - val_loss: 1.7590 - val_accuracy: 0.5096
Epoch 5/10
91/91 [==============================] - 5s 49ms/step - loss: 0.0352 - accuracy: 0.9914 - val_loss: 1.8886 - val_accuracy: 0.5096
Epoch 6/10
91/91 [==============================] - 4s 49ms/step - loss: 0.0379 - accuracy: 0.9904 - val_loss: 1.7689 - val_accuracy: 0.5510
Epoch 7/10
91/91 [==============================] - 3s 30ms/step - loss: 0.0221 - accuracy: 0.9952 - val_loss: 1.9934 - val_accuracy: 0.5152
Epoch 8/10
9

In [387]:
# Make predictions on the validation dataset
model_2_pred_probs = model_2.predict(test_tweet)
model_2_pred_probs.shape, model_2_pred_probs[:10] # view the first 10

23/23 [==============================] - 1s 8ms/step


((726, 3),
 array([[9.4331364e-04, 9.9865472e-01, 4.0192698e-04],
        [9.5303549e-04, 9.9851030e-01, 5.3656480e-04],
        [1.2956156e-01, 2.9451847e-01, 5.7592005e-01],
        [8.3249499e-04, 9.9877971e-01, 3.8781611e-04],
        [6.7629555e-04, 9.9876690e-01, 5.5685337e-04],
        [5.2684691e-04, 1.2362162e-03, 9.9823689e-01],
        [9.9876899e-01, 6.0907518e-04, 6.2186603e-04],
        [9.6679106e-04, 9.9693120e-01, 2.1019655e-03],
        [9.9731147e-01, 1.4412673e-03, 1.2473000e-03],
        [1.4879756e-03, 2.1395657e-02, 9.7711641e-01]], dtype=float32))

In [388]:
model_2_preds = tf.squeeze(tf.round(model_2_pred_probs))
model_2_preds = np.argmax(model_2_preds, axis=1)

In [389]:
test_sentimen

array([1, 1, 0, 1, 1, 2, 0, 1, 0, 2, 1, 1, 1, 2, 0, 1, 2, 2, 1, 1, 0, 2,
       0, 1, 0, 1, 1, 2, 0, 2, 0, 1, 1, 2, 1, 1, 2, 1, 2, 0, 1, 1, 1, 0,
       0, 0, 0, 2, 1, 1, 2, 1, 0, 1, 1, 1, 0, 0, 0, 2, 2, 1, 2, 2, 0, 1,
       1, 2, 0, 1, 1, 2, 0, 1, 2, 2, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 1, 0, 0, 0, 2, 0, 1, 2, 1, 0, 1,
       1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 2, 0, 2, 1, 0, 1, 2, 0, 0, 1, 1, 1,
       1, 2, 2, 2, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 2, 2, 1,
       2, 1, 2, 2, 1, 0, 0, 1, 2, 2, 2, 1, 2, 0, 2, 2, 0, 1, 1, 0, 1, 2,
       2, 2, 1, 2, 1, 0, 2, 2, 0, 0, 1, 2, 2, 2, 0, 1, 1, 0, 1, 2, 1, 2,
       1, 0, 1, 1, 2, 2, 0, 0, 0, 1, 0, 2, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1,
       2, 0, 2, 1, 2, 1, 0, 1, 0, 1, 2, 0, 1, 1, 2, 0, 2, 0, 1, 1, 1, 2,
       2, 1, 2, 2, 2, 0, 2, 2, 1, 2, 2, 0, 0, 2, 1, 0, 0, 2, 2, 1, 0, 2,
       0, 1, 0, 1, 0, 0, 2, 0, 2, 1, 2, 1, 1, 0, 2, 2, 2, 2, 0, 1, 2, 2,
       1, 1, 0, 2, 2, 0, 0, 2, 1, 0, 1, 2, 1, 1, 0,

In [390]:
# Calculate LSTM model results
model_2_results = calculate_results(y_true=test_sentimen,
                                    y_pred=model_2_preds)
model_2_results

{'accuracy': 90.633608815427,
 'precision': 0.9081001847915401,
 'recall': 0.90633608815427,
 'f1': 0.9061256462780763}

In [397]:
np.array(['halo'])

array(['halo'], dtype='<U4')

In [ ]:
model_2_pred_probs = model_2.predict(test_tweet)

In [410]:
tf.squeeze(tf.round(model_2.predict(np.array(['Pak @sandiuno dan pak @prabowo Gajinya kirim ke saya sj'])))).numpy()

1/1 [==============================] - 0s 37ms/step


array([0., 0., 1.], dtype=float32)

In [411]:
df_test

sentimen  \
1207         0   
1550         1   
865          1   
141          1   
829          1   
...        ...   
811          0   
1254         2   
100          0   
1576         1   
928          1   

                                                                                                                                                                                                                                                                                                                                                                                                       tweet  
1207                                                                                                                                                           Nge hack punya profesor saididu? dibayar jokowi ya? Tujuannya apa sih? Ilmu digunakan ke hal yg positif lebih berharga. akun orang, gak perlu kau handle.  @jokowi @Jokowi_Amin @JokowiCentre pekerjaan ini apa ya namanya? Fitnah atau hoax?  
1550                                                                                                                                                                                                                                                         Setuju, karena juga sudah diakui Pak @prabowo kalau Rel ekonomi kita sudah benar dibawah pemerintahan pak @jokowi .  pic.twitter.com/gFNyubXTch  
865                                                                                                                                                                                                                                                                                                                              Pancasila harga mati bravo pak presiden @jokowi  pic.twitter.com/knQYLidaeC  
141   Presiden Jokowi dan Raja Salman bin Abdulaziz al-Saud melakukan pertemuan bilateral. Keduanya sepakat akan meningkatkan kerja sama di bidang ekonomi.  https://news.detik.com/berita/d-4510595/menlu-retno-ri-saudi-tingatkan-kerjasama-di-sektor-energi-dan-pariwisata?utm_term=echoboxauto&utm_campaign=detikcomsocmed&utm_medium=oa&utm_content=detikcom&utm_source=Twitter#Echobox=1555270554 …  
829                                                                                                                                                                                                         Nyo buka youtube. Dngerin sekali lg yg ditanyain pak jokowi. Yg jd pembahasan awal kan bkn masalah e sport tapi pokok utamanya adl ekonomi digital. Dan Mobile legend cm jadi salah satu contoh.  
...                                                                                                                                                                                                                                                                                                                                                                                                      ...  
811                                                                                                                                                                                                   Klo org korea, singapore, australia mau jokowi silahkan ambil. Faktanya di jaman beliau: pertumbuhan ekonomi melambat, laju penurunan masy miskin melambat, rekor terburuk defisit neraca perdagangan.  
1254                                                                                                                                                                                                                                                                                  Pak @sandiuno dan pak @prabowo Gajinya kirim ke saya sj.  https://twitter.com/detikcom/status/1117096753759686657 …  
100                                                                                                                                                                                                   